name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch: 
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Add remote
        run: git remote add space https://huggingface.co/spaces/etisam1/mlops

      - name: Set Hugging Face token for git push
        run: |
          git config --global credential.helper store
          echo "https://etisam1:${{ secrets.HF_TOKEN }}@huggingface.co" > ~/.git-credentials

      - name: Push to hub
        run: git push --force https://huggingface.co/spaces/etisam1/mlops main
